version: "3.8"
services: 
    
    #==============================================>> Database
    mysql: 
        image: mysql:5.7.36
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "8001:3306"
        environment:
            MYSQL_DATABASE: mysql
            MYSQl_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db/mysql:/var/lib/mysql
        networks:
            - ip_pos

    #==============================================>> API
    api: 
        container_name: ip-pos-api
        restart: unless-stopped
        tty: true
        build: 
            context: ./api/.
            dockerfile: Dockerfile
        volumes: 
            - ./api/app:/var/www/app
            - ./api/resources:/var/www/resources
            - ./api/routes:/var/www/routes
            - ./api/storage:/var/www/storage
            - ./api/database:/var/www/database
        command: php artisan --host=0.0.0.0 serve
        ports:
            - "8002:8000"
        environment: 
            #===========================>> JWT
            JWT_SECRET: MTO7OmBzXhbPI2bErLjV9XEFbpCn3MHCPxKdcBxiFHjuWJirIayTB9npa4cGNAFX

            #===========================>> Telegram Bot
            TELEGRAM_BOT_TOKEN          : 6314774488:AAH5aPvR3-7Gh5ti3S9tksCbSVEwR-p9eWQ
            TELEGRAM_CHAT_ID_ORDER      : -1002006933625
            TELEGRAM_CHAT_ID_ACCOUNT    : -1002105459915
            TELEGRAM_CHAT_ID_LOGIN_LOGS : -1001954497247

            #===========================>> Mail
            MAIL_MAILER       : smtp
            MAIL_HOST         : smtp.gmail.com
            MAIL_PORT         : 587
            MAIL_USERNAME     : tongmeng016@gmail.com
            MAIL_PASSWORD     : nwajfntckkflumar
            MAIL_ENCRYPTION   : ssl
            MAIL_FROM_ADDRESS : "tongmeng016@gmail.com"
            MAIL_FROM_NAME    : ${Your_Name}

            #==========================>> APP_KEY
            APP_KEY: base64:yO7SSlNCR6TlaOiH/xWiWI41I2pAL6q0bHGMos1hvB4=


            #==========================>> DB Config
            DB_CONNECTION: mysql
            DB_HOST: mysql #DB_HOST
            DB_PORT: 3306
            DB_DATABASE: Awesome-Shoes
            DB_USERNAME: root
            DB_PASSWORD: secret

            #==========================>> FILE
            FILE_URL: http://file:8000

        networks: 
            - ip_pos

    #==============================================>> File
    file: 
        container_name: ip-pos-file  
        build: 
            context: ./file/.
            dockerfile: Dockerfile
        volumes: 
            - ./file/public:/var/www/public
        command: php artisan --host=0.0.0.0 serve
        ports:
            - "8003:8000"
        networks: 
            - ip_pos

    web: 
        container_name: ip-pos-web
        build:
            context: ./admin_dashboard/.
            dockerfile: Dockerfile
        ports:
            - "8005:80"
        networks: 
            - ip_pos
networks: 
    ip_pos: